### ISSUE TITLE
Incorrect file name in conversion response service

### ISSUE THREAD

**Issue by kiruxaspb** [singnet/snet-converter-services#112]
We have a file: [conversion_reponse.py](https://github.com/singnet/snet-converter-services/blob/master/application/service/conversion_reponse.py)

with bad name: `conversion_REPONSE.py`, but it should have name `conversion_RESPONSE.py`

I think it will need to be renamed for sure.

**Comment by sassless** [comment]
Fixed in PR https://github.com/singnet/snet-converter-services/pull/123

**Comment by kiruxaspb** [comment]
Closed for https://github.com/singnet/snet-converter-services/pull/123
